/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next/components/BButton')['BButtonGroup']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BFormSelect: typeof import('bootstrap-vue-next/components/BFormSelect')['BFormSelect']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTab: typeof import('bootstrap-vue-next/components/BTabs')['BTab']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BTabs: typeof import('bootstrap-vue-next/components/BTabs')['BTabs']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab1Component: typeof import('./src/components/tabs/Tab1Component.vue')['default']
    Tab2Component: typeof import('./src/components/tabs/Tab2Component.vue')['default']
    Tab3Component: typeof import('./src/components/tabs/Tab3Component.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
